.github/workflows/build-push.yml
Attempt to fix following:
```
#11 ERROR: denied: permission_denied: The requested installation does not exist.
------
> pushing ghcr.io/ynezz/buildworker-v3.5.0:master with docker:
------
ERROR: denied: permission_denied: The requested installation does not exist.
Error: buildx failed with: ERROR: denied: permission_denied: The requested installation does not exist.
```
References: https://github.com/openwrt/buildbot/actions/runs/4971701948/jobs/8899889081#step:9:191
=> ci: fix ghcr.io container pushing

phase1/master.cfg
Currently every 1st build on ephemeral build worker results in the failure of the `gitverify` build step as the stock buildbot Git() build step for some reasons just clones the Git repository into detached HEAD state.
On the 2nd build using the same build worker Git() checkouts the branch and thus makes `gitverify` step happy and the builds then continues normally.
This needs to be fixed properly, either by adjusting the `gitverify` check or adding suitable `mode` into Git() build step, but this needs more time and testing.
So for now, lets simply workaround that issue by running Git() step two times.
References: #5
=> phase1: workaround gitverify 1st build failures on fresh workers

phase1/master.cfg
These 3 rm steps are unnecessary since these folders are already cleaned by the Git() step. Thus reduce clutter in already pretty busy Factory.
=> phase1: cleanup redundant steps

phase1/master.cfg
dlprune currently fails [with following error](https://buildbot.staging.openwrt.org/images/#/builders/101/builds/10):
```
find: cannot delete ‘dl/’: Not a directory
```
Initial idea was to delete only files and not the download directory itself, so lets adjust the find command accordingly.
Fixes: 68b20ed67b5e ("phase1: prune unused files from dl/")
=> phase1: dlprune: fix cannot delete ‘dl/’: Not a directory

.github/workflows/build-push.yml, phase1/master.cfg
@robimarko noticed, that after rename of `ipq807x` target in main branch to `qualcommax/ipq807x` subtarget, that buildbot is trying to build this new `qualcommax/ipq807x` subtarget on `openwrt-23.05` branch as well.
@f00b4r0  [later explained](https://github.com/openwrt/buildbot/issues/14#issuecomment-1595839703), that this is by design, his initial idea was to find exhaustive list of all targets and let the `checkarch` step do the final triaging.
I find this approach confusing, because if the subtarget is not present in that branch, we shouldn't have builder for it configured as well. Furthermore wasting roughly 5 minutes of precious buildworker time to checkout all feeds and then just find out, that we're not going to use those seems suboptimal as well.
So lets fix it by using builders …
=> phase1: fix leaking targets between branches

docker/buildworker/Dockerfile
UBoot version of at least 2023.07.02 that use binman also have a dependency of pyelftools on the build host.
=> docker,worker: install pyelftools

.github/workflows/build-push.yml
Improve and refactor some part of the workflow to better organize it and use github deploy feature.
The final result on a running push is the following
---
@ynezz my only question is what we should use as tag... Is "production" ok? We can use whatever we want... Also buildbot.
Aside from this, it's just a cleanup and improvement.
Also also... Should we change the short version for git to 12? Using 8 has been deprecated... No idea if it does cause problems.
=> ci: generic improvement and cleanup of workflow

.github/workflows/build-push.yml, phase1/master.cfg
Currently the buildmaster would only order tag builds within their own branch, meaning that if e.g. a higher priority branch has normal buildrequests (i.e. buildrequests comming from the AnyBranchScheduler), and a lower priority branch has "tag" buildrequests (i.e. from the Triggerable scheduler), the former builderequests would be served first, deferring the build of e.g. release tags.
We want forced builds (release tag) to have maximum priority, regardless of branch priority. This commit attempts to solve this problem by leveraging the newly (as of buildbot 3.9.0) introduced "priority" scheduler parameter, by raising the Triggerable scheduler buildrequests priority, and then considering this higher priority in Builders' order.
The net result is that Builders are now prioritized if they …
=> phase1: raise priority of tag builds

phase2/master.cfg
Hopefully fix "make -j6.0" instead of "make -j6"
=> phase2: max_builds is always set to 1

docker/config.ini, phase2/config.ini.example, phase2/master.cfg
Update default sdk pattern to a more relaxed pattern to make it future proof if in the future the compression extension will change again.
Needed currently with the migration from .xz to .zst.
---
@ynezz  @f00b4r0 Can you guys also update the config.ini to point to the new pattern (if that is defined in our config?)
Or eventually if it's not and we can't push a new release, can we add the entry since that is configurable?
=> phase2: update default sdk pattern to a more relaxed pattern

.github/workflows/build-push.yml
This reverts commit 44ed9a39fddc4e79ec1276c3e5923766cbe19878 as it breaks GitPoller.
References: https://github.com/buildbot/buildbot/issues/7663
=> Revert "Bump buildbot to v3.11.3 release"

phase1/config.ini.example, phase1/master.cfg
Currently we always populate builders (build targets) from the Git tree,
but for staging environment this is usually overkill as we might need
just a bunch of targets, so lets make this configurable.
=> phase1: make list of builders configurable

phase1/config.ini.example, phase1/master.cfg
The AnyBranchScheduler will currently wait for 15 minutes before starting a build.  If new changes are made on the same branch during this interval, the timer will be restarted.
For staging repository we want faster feedback loop, so we're going to use much lower value, thus lets make this configurable and handled via Ansible.
=> phase1: AnyBranchScheduler: make treeStableTimer configurable

phase1/master.cfg
Ansuel reported, that with `USE_APK=y` there are no kmods available in the build artifacts, so lets fix it by extending the rsync's include pattern with the `apk` suffix to make it future proof.
Reported-by: Christian Marangi <ansuelsmth@gmail.com>
=> phase1: kmodprepare: add apk compat

phase1/master.cfg
=> phase1: make IsNoMasterBuild function more flexible

docker/config.ini, docker/rsync/Dockerfile, phase1/config.ini.example, phase1/master.cfg, phase2/config.ini.example, phase2/master.cfg, scripts/signall.sh
With this commit it's possible to sign APK package indexes (packages.adb) via the `signall.sh` script, which is run on the buildmaster. As a consequence `apk` must be available on the buildmaster. This is the final step to replace OPKG with APK.
=> add APK signing logic

docker/buildmaster/Dockerfile, tests/cram/master/02-apk.t
We need apk to sign packages.adb, this is unreleased version introduced in commit ef8c1adb6118 ("apk: switch to index-trust branch"), thus not available already anywhere yet. So until its available, lets build a static version and use that meanwhile.
Fixes: a94d4e15fdc1 ("add APK signing logic")
=> buildmaster: add static apk utility

.github/workflows/build-push.yml, docker/buildworker/files/start.sh
Workers are currently refusing to work:
```python
Unhandled Error
Traceback (most recent call last):
File "/opt/venv/lib/python3.11/site-packages/twisted/application/app.py", line 673, in run
runApp(config)
File "/opt/venv/lib/python3.11/site-packages/twisted/scripts/twistd.py", line 29, in runApp
runner.run()
File "/opt/venv/lib/python3.11/site-packages/twisted/application/app.py", line 370, in run
self.application = self.createOrGetApplication()
File "/opt/venv/lib/python3.11/site-packages/twisted/application/app.py", line 437, in createOrGetApplication
application = getApplication(self.config, passphrase)
--- <exception caught here> ---
File "/opt/venv/lib/python3.11/site-packages/twisted/application/app.py", line 446, in getApplication
application = service.loadApplication(filename, …
```
=> buildworker: start: fix worker startup failure after update

docker/buildworker/Dockerfile
In Debian 11 (Bullseye), the `file` package was installed indirectly because the `man-db` package recommended it. The `man-db` package is often installed as a dependency of other packages, such as `build-essential` and tools like `gcc` and `make`.  By default, `apt-get` installs recommended packages, so `file` was installed automatically.
Starting from Debian 12 (Bookworm), the `man-db` package no longer recommends the `file` package. This change was made to reduce the size of minimal container images and installations where `file` is not essential.
So lets install this package explicitly.
=> docker: buildworker: add missing file package

.github/workflows/build-push.yml
In commit 3ac7d39bd4c3 ("buildworker,buildmaster: bump Debian to version
12") we switched the base system to Debian 12 which uses Python 3.11.2,
thus lets test on CI with same version.
---
Bug fixes
---------
- Made Tags column in Builders page take less space when there are no tags.
- Fixed cropped change author avatar image in web UI.
- Correctly pluralize build count in build summaries in the web UI.
- The change details page no longer requires an additional mouse click to show the change details.
- Fixed showing misleading "Loading" spinner when a change has no builds.
- Fixed too small spacing in change header text in web UI.
- Fixed showing erroneous zero changes count in the web UI when loading changes.
- Cleaned up build and worker tabs in builders view in web UI.
- Improved …
=> Bump buildbot to v3.11.8 release, use main branch on CI and Python 3.11 

phase1/master.cfg, phase2/master.cfg
Currently the sha256sum verification of apk's packages.adb index
fails as the file is modified with `apk adbsign`, but we currently don't
send the sha256sums file to the master, thus it can't be fixed during
signing.
So lets pack sha256sums files and ship them to master for proper
signing.
Fixes: https://github.com/openwrt/buildbot/commit/a94d4e15fdc1e9715d7d0cfdcc62227186d0fc45 ("add APK signing logic")
=> phase2: signpack: fix sha256sums signatures of apk packages.adb index

docker/buildworker/Dockerfile
Addition of OPTEE support along with STM32 added a requirment on python3-cryptography and without it buildbots for STM32 will fail with:
```
Checking 'python3-cryptography'... failed.
Checking 'python3-pyelftools'... ok.
optee-os: Please install the Python3 cryptography module make[3]: *** [/builder/shared-workdir/build/include/prereq.mk:9: prereq] Error 1
```
So install python3-cryptography to satisfy it.
=> docker,worker: install python3-cryptography
